### ISSUE TITLE
This plugin generated a warning from the characteristic

### ISSUE THREAD

**Issue by schioth** [techyowl/homebridge-august-smart-locks#45]
[28/03/2021, 22:14:21] [homebridge-august-smart-locks] Error: 
    at LockTargetState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at LockTargetState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at LockTargetState.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at AugustPlatform.updatelockStates (/usr/local/lib/node_modules/homebridge-august-smart-locks/platform.js:238:72)
    at /usr/local/lib/node_modules/homebridge-august-smart-locks/platform.js:86:16
    at /usr/local/lib/node_modules/homebridge-august-smart-locks/platform.js:504:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by derouin89** [comment]
i get 
[5/2/2021, 8:42:28 PM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Lock Target State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by dxdc** [comment]
I have several warnings regarding the battery, e.g.:

```
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:47 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:48 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
1|homebridge      | [5/4/2021, 10:18:48 AM] [homebridge-august-smart-locks] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
```

**Comment by scottrus** [comment]
Opened PR #53 to fix the "Lock Target State" characteristic.

**Comment by EarmarkedHuman** [comment]
any resolution to this? I'm getting the same message.

**Comment by techyowl** [comment]
update to 5.1.0
